[git]
commit_parsers = [
  { message = "^Merge", skip = true },
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore\\(deps\\)", skip = true },
  { message = "^feat", group = "🚀 Features" },
  { message = "^fix", group = "🐛 Bug Fixes" },
  { message = "^doc", group = "📝 Documentation" },
  { message = "^perf", group = "⚡ Performance" },
  { message = "^refactor", group = "🏗️ Refactor" },
  { message = "^style", group = "🎨 Styling" },
  { message = "^test", group = "✅ Testing" },
  { message = "^chore", group = "⚙️ Miscellaneous Tasks" },
  { body = ".*security", group = "🔒 Security" },
]

conventional_commits = false
filter_commits = true
tag_pattern = "v[0-9]*"
# protect commits from being skipped due to matching skip patterns
protect_breaking_commits = true
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"

[changelog]
# changelog header
header = """
# Changelog
All notable changes to this project will be documented in this file.

"""
# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{% for group, commits in commits | group_by(attribute="group") %}
    {{ group | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.breaking -%}
            {% raw %}**BREAKING:** {% endraw %}\
        {% endif -%}
            {{ commit.message | upper_first }}\
            {% if commit.remote.github.username %} by @{{ commit.remote.github.username }}{%- endif -%}
            {% if commit.remote.github.pr_number %} in #{{ commit.remote.github.pr_number }}{%- endif -%}
    {% endfor %}
{% endfor %}

{% if previous.version -%}
    **Full Changelog**: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ previous.version }}...{{ version }}
{% endif %}
"""
# remove the leading and trailing whitespace from the template
trim = true
# changelog footer
footer = """
<!-- generated by git-cliff -->
"""

[bump]
features_always_bump = true
breaking_always_bump = true

[remote.github]
owner = "yinheli"
repo = "kungfu"
