# static routes
# static routes is not enable to hot reload
- type: route
  target: hk
  values:
    - 149.154.160.0/20
    - 149.154.167.0/24
    - 149.154.164.0/22
    - 109.239.140.0/24
    - 91.108.56.0/22
    - 91.108.4.0/22
    - 91.108.8.0/22

# domain pattern base glob
- type: domain
  target: hk
  values:
    - "*google.com"
    - "*facebook.com"

# upstream CIDR match
- type: dnsCidr
  target: hk
  values:
    - 39.156.69.79/32
    - 220.181.38.148/32

# upstream IP GEO
# base https://dev.maxmind.com/geoip/geoip2/geolite2
# https://github.com/P3TERX/GeoLite.mmdb
# TODO support
- type: dnsGeoIp
  target: hk
  values:
    - hk
    - us
